"use client";

import {
  Download,
  Eye,
  Pencil,
  Plus,
  Power,
  PowerOff,
  RotateCcw,
  Trash2,
  Upload,
} from "lucide-react";
import type { ChangeEvent, FormEvent, ReactNode } from "react";
import {
  useCallback,
  useDeferredValue,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import { requestAdminApi } from "@/lib/admin-api";
import {
  defaultAdminDashboardConfig,
  type AdminDashboardConfigData,
} from "@/lib/admin-dashboard-config";
import {
  exportAdminTeachersCsv,
  fetchAdminTeachers,
  type AdminTeachersSummary,
} from "@/lib/admin-directory";
import { cn } from "@/lib/utils";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

import type { AdminTeacher } from "./admin-data";
import {
  AdminDataTable,
  type AdminColumnDefinition,
} from "./components/AdminDataTable";
import { AdminPaginationFooter } from "./components/AdminPaginationFooter";
import { AdminSummaryLineSkeleton } from "./components/AdminLoadingState";
import { AdminSectionCard } from "./components/AdminSectionCard";
import { AdminStatusBadge } from "./components/AdminStatusBadge";

type AdminTeachersProps = {
  dashboardConfig?: AdminDashboardConfigData;
  onRefresh?: () => Promise<void> | void;
  globalSearchQuery?: string;
};

type TeacherFormValues = {
  name: string;
  email: string;
  password: string;
  subject: string;
  branch: string;
  phone: string;
  schedule: string;
  activeClasses: string;
  classList: string;
  status: AdminTeacher["status"];
  availability: AdminTeacher["availability"];
};

type TeacherStatusFilterOption = AdminTeacher["status"] | "Semua";

type TeacherImportSummary = {
  totalRows: number;
  importedRows: number;
  failedRows: number;
  skippedRows: number;
};

type TeacherImportDetail = {
  rowNumber: number;
  name: string;
  subject: string;
  branch: string;
  status: "imported" | "failed" | "skipped";
  email?: string;
  loginCode?: string;
  generatedPassword?: string;
  reason?: string;
};

type TeacherImportResponse = {
  fileName: string;
  sheetName: string;
  summary: TeacherImportSummary;
  details: TeacherImportDetail[];
};

type BranchApiItem = {
  name?: string;
};

type TeacherCreateGeneratedCredentials = {
  email: string;
  loginCode: string;
  password: string;
  autoGeneratedEmail: boolean;
  autoGeneratedPassword: boolean;
};

type TeacherCreateResponse = {
  teacher: AdminTeacher;
  generatedCredentials?: TeacherCreateGeneratedCredentials;
};

type TeacherCreatedAccount = {
  teacherId: string;
  teacherName: string;
  email: string;
  loginCode: string;
  password: string;
  autoGeneratedEmail: boolean;
  autoGeneratedPassword: boolean;
};

const allBranchesLabel = "Semua cabang";
const teacherImportColumns = [
  "nama guru",
  "bidang/mapel",
  "pendidikan terakhir",
  "cabang",
] as const;
const warmFieldClassName =
  "border-slate-200 hover:border-orange-200 focus:border-orange-300 focus:ring-4 focus:ring-orange-500/10 focus-visible:border-orange-300 focus-visible:ring-4 focus-visible:ring-orange-500/10";
const warmSelectTriggerClassName =
  "border-slate-200 hover:border-orange-200 focus:border-orange-300 focus:ring-4 focus:ring-orange-500/10 focus-visible:border-orange-300 focus-visible:ring-4 focus-visible:ring-orange-500/10 data-[state=open]:border-orange-300 data-[state=open]:ring-4 data-[state=open]:ring-orange-500/10";
const warmSelectContentClassName =
  "border-orange-100/80 shadow-lg shadow-orange-100/20";
const warmSelectItemClassName =
  "hover:bg-orange-50 hover:text-orange-700 focus:bg-orange-50 focus:text-orange-700 data-[highlighted]:bg-orange-50 data-[highlighted]:text-orange-700 data-[state=checked]:bg-orange-50 data-[state=checked]:text-orange-700";
const warmOutlineButtonClassName =
  "border-slate-200 bg-white text-slate-700 hover:border-orange-200 hover:bg-orange-50 hover:text-orange-700 active:border-orange-300 active:bg-orange-100/80 active:text-orange-800 focus-visible:border-orange-300 focus-visible:ring-orange-500/10";
const warmPrimaryButtonClassName =
  "bg-orange-600 hover:bg-orange-700 active:bg-orange-800 focus-visible:ring-orange-500/20";
const warmOverlayPanelClassName =
  "[&>button]:hover:bg-orange-50 [&>button]:hover:text-orange-700 [&>button]:focus-visible:ring-orange-500/10";
const warmAvatarFallbackClassName =
  "bg-gradient-to-br from-orange-500 to-amber-400";
const warmFileInputClassName =
  "block w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-700 outline-none transition hover:border-orange-200 focus:border-orange-300 focus:ring-4 focus:ring-orange-500/10 focus-visible:border-orange-300 focus-visible:ring-4 focus-visible:ring-orange-500/10 file:mr-4 file:rounded-xl file:border-0 file:bg-orange-50 file:px-3 file:py-2 file:text-sm file:font-medium file:text-orange-700";

function getInitials(name: string) {
  return name
    .split(" ")
    .filter(Boolean)
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
}

function normalizeText(value: string) {
  return value.trim().replace(/\s+/g, " ");
}

function normalizeEmail(value: string) {
  return value.trim().toLowerCase();
}

function normalizePhone(value: string) {
  return value.trim().replace(/\s+/g, "");
}

function normalizeClassList(value: string) {
  return value
    .split(/\r?\n|,/)
    .map((item) => item.trim())
    .filter(Boolean)
    .join(", ");
}

function normalizeActiveClasses(value: string) {
  const trimmedValue = value.trim();

  if (!trimmedValue || !/^\d+$/.test(trimmedValue)) {
    return null;
  }

  return Number(trimmedValue);
}

function buildBranchOptions(values: string[]) {
  return Array.from(
    new Set(values.map((value) => normalizeText(value)).filter(Boolean)),
  ).sort((left, right) => left.localeCompare(right, "id"));
}

function getTeacherBranches(
  teacher: Pick<AdminTeacher, "branch" | "branches">,
  availableBranches?: string[],
) {
  const branches = Array.from(
    new Set(
      [...(teacher.branches ?? []), teacher.branch]
        .map((branch) => normalizeText(branch))
        .filter(Boolean),
    ),
  );

  if (!availableBranches) {
    return branches;
  }

  return branches
    .map((branch) => normalizeTeacherBranch(branch, availableBranches))
    .filter((branch): branch is string => Boolean(branch));
}

function getTeacherBranchesLabel(
  teacher: Pick<AdminTeacher, "branch" | "branches">,
  availableBranches?: string[],
) {
  if (availableBranches) {
    return (
      getTeacherBranches(teacher, availableBranches).join(" - ") ||
      "Cabang belum diatur"
    );
  }

  return getTeacherBranches(teacher).join(" • ") || "Cabang belum diatur";
}

function normalizeTeacherBranch(value: string, availableBranches: string[]) {
  const normalizedValue = normalizeText(value).toLowerCase();

  if (!normalizedValue) {
    return null;
  }

  return (
    availableBranches.find(
      (branch) => normalizeText(branch).toLowerCase() === normalizedValue,
    ) ?? null
  );
}

function getDefaultBranch(availableBranches: string[]) {
  return availableBranches[0] ?? "";
}

function createEmptyTeacherForm(
  defaultBranch = "",
  defaultAvailability: AdminTeacher["availability"] = "Tersedia",
): TeacherFormValues {
  return {
    name: "",
    email: "",
    password: "",
    subject: "",
    branch: defaultBranch,
    phone: "",
    schedule: "-",
    activeClasses: "0",
    classList: "",
    status: "Aktif",
    availability: defaultAvailability,
  };
}

function toTeacherFormValues(
  teacher: AdminTeacher,
  availableBranches: string[],
): TeacherFormValues {
  return {
    name: teacher.name,
    email: teacher.email,
    password: "",
    subject: teacher.subject,
    branch:
      normalizeTeacherBranch(teacher.branch, availableBranches) ??
      getDefaultBranch(availableBranches),
    phone: teacher.phone,
    schedule: teacher.schedule,
    activeClasses: String(teacher.activeClasses),
    classList: teacher.classList,
    status: teacher.status,
    availability: teacher.availability,
  };
}

function readFileAsDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = () => {
      if (typeof reader.result === "string") {
        resolve(reader.result);
        return;
      }

      reject(new Error("File import guru tidak dapat dibaca."));
    };
    reader.onerror = () => {
      reject(new Error("File import guru tidak dapat dibaca."));
    };
    reader.readAsDataURL(file);
  });
}

function TeacherField({
  label,
  children,
}: {
  label: string;
  children: ReactNode;
}) {
  return (
    <div className="space-y-2">
      <p className="text-sm font-medium text-slate-700">{label}</p>
      {children}
    </div>
  );
}

function DetailItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-[20px] border border-slate-200/80 bg-white/95 p-4 shadow-[0_12px_26px_-22px_rgba(15,23,42,0.14)]">
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">
        {label}
      </p>
      <p className="mt-2 text-sm font-medium text-slate-800">{value}</p>
    </div>
  );
}

function TeacherActions({
  teacher,
  branchOptions,
  onEdit,
  onDelete,
  onToggleStatus,
}: {
  teacher: AdminTeacher;
  branchOptions: string[];
  onEdit: (teacher: AdminTeacher) => void;
  onDelete: (teacher: AdminTeacher) => void;
  onToggleStatus: (teacher: AdminTeacher) => void;
}) {
  return (
    <div className="flex items-center justify-center gap-1.5">
      <Sheet>
        <SheetTrigger asChild>
          <Button
            type="button"
            variant="outline"
            size="icon"
            className={`size-9 rounded-xl p-0 text-slate-500 shadow-sm transition ${warmOutlineButtonClassName}`}
            aria-label={`Lihat detail ${teacher.name}`}
            title="Detail"
          >
            <Eye className="size-4" />
          </Button>
        </SheetTrigger>
        <SheetContent
          side="right"
          className={`w-[92vw] overflow-y-auto sm:max-w-lg ${warmOverlayPanelClassName}`}
        >
          <SheetHeader>
            <SheetTitle>Detail guru</SheetTitle>
            <SheetDescription>
              Ringkasan profil guru, distribusi kelas aktif, dan status
              ketersediaan mengajar.
            </SheetDescription>
          </SheetHeader>
          <div className="mt-6 space-y-5">
            <div className="flex items-center gap-4 rounded-[22px] border border-orange-100/70 bg-gradient-to-r from-orange-50/85 to-white p-4 shadow-[0_16px_32px_-24px_rgba(249,115,22,0.22)]">
              <Avatar className="size-14 rounded-full">
                <AvatarFallback className={cn(warmAvatarFallbackClassName, "rounded-full")}>
                  {getInitials(teacher.name)}
                </AvatarFallback>
              </Avatar>
              <div className="min-w-0">
                <p className="text-base font-semibold text-slate-950">
                  {teacher.name}
                </p>
                <p className="truncate text-sm text-slate-500">
                  {teacher.subject}
                </p>
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <DetailItem label="Kode Login" value={teacher.loginCode || teacher.id} />
              <DetailItem label="Email Internal" value={teacher.email} />
              <DetailItem label="Mapel" value={teacher.subject} />
              <DetailItem
                label="Cabang"
                value={getTeacherBranchesLabel(teacher, branchOptions)}
              />
              <DetailItem label="Jadwal" value={teacher.schedule} />
              <DetailItem
                label="Kelas aktif"
                value={`${teacher.activeClasses} kelas`}
              />
              <DetailItem label="ID Guru" value={teacher.id} />
            </div>

            <div className="rounded-[20px] border border-slate-200/80 bg-white/95 p-4 shadow-[0_12px_26px_-22px_rgba(15,23,42,0.14)]">
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">
                Kelas yang diampu
              </p>
              <p className="mt-2 text-sm leading-6 text-slate-700">
                {teacher.classList}
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-3">
              <AdminStatusBadge status={teacher.status} />
              <AdminStatusBadge status={teacher.availability} />
            </div>
          </div>
        </SheetContent>
      </Sheet>

      <Button
        type="button"
        variant="outline"
        size="icon"
        className={`size-9 rounded-xl p-0 text-orange-600 shadow-sm transition ${warmOutlineButtonClassName}`}
        aria-label={`Edit ${teacher.name}`}
        title="Edit"
        onClick={() => onEdit(teacher)}
      >
        <Pencil className="size-4" />
      </Button>

      <Button
        type="button"
        variant="outline"
        size="icon"
        className={
          teacher.status === "Aktif"
            ? "size-9 rounded-xl border-amber-200 bg-white p-0 text-amber-600 shadow-sm transition hover:border-amber-300 hover:bg-amber-50 hover:text-amber-700 active:border-amber-300 active:bg-amber-100/80 focus-visible:ring-orange-500/10"
            : "size-9 rounded-xl border-emerald-200 bg-white p-0 text-emerald-600 shadow-sm transition hover:border-emerald-300 hover:bg-emerald-50 hover:text-emerald-700 active:border-emerald-300 active:bg-emerald-100/80 focus-visible:ring-orange-500/10"
        }
        aria-label={
          teacher.status === "Aktif"
            ? `Nonaktifkan ${teacher.name}`
            : `Aktifkan ${teacher.name}`
        }
        title={teacher.status === "Aktif" ? "Nonaktifkan" : "Aktifkan"}
        onClick={() => onToggleStatus(teacher)}
      >
        {teacher.status === "Aktif" ? (
          <PowerOff className="size-4" />
        ) : (
          <Power className="size-4" />
        )}
      </Button>

      <Button
        type="button"
        variant="outline"
        size="icon"
        className="size-9 rounded-xl border-rose-200 bg-white p-0 text-rose-600 shadow-sm transition hover:border-rose-300 hover:bg-rose-50 hover:text-rose-700 active:border-rose-300 active:bg-rose-100/80 focus-visible:ring-orange-500/10"
        aria-label={`Hapus ${teacher.name}`}
        title="Hapus"
        onClick={() => onDelete(teacher)}
      >
        <Trash2 className="size-4" />
      </Button>
    </div>
  );
}

export function AdminTeachers({
  dashboardConfig = defaultAdminDashboardConfig,
  onRefresh,
  globalSearchQuery = "",
}: AdminTeachersProps) {
  const teacherStatusOptions: TeacherStatusFilterOption[] = [
    "Semua",
    ...dashboardConfig.teacher.statuses,
  ];
  const teacherAvailabilityOptions = dashboardConfig.teacher.availabilities;
  const teacherSubjectOptions = dashboardConfig.schedule.subjects;
  const defaultTeacherAvailability =
    teacherAvailabilityOptions[0] ?? "Tersedia";
  const [teachers, setTeachers] = useState<AdminTeacher[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [branchFilter, setBranchFilter] = useState(allBranchesLabel);
  const [statusFilter, setStatusFilter] =
    useState<TeacherStatusFilterOption>("Semua");
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isImportOpen, setIsImportOpen] = useState(false);
  const [editingTeacherId, setEditingTeacherId] = useState<string | null>(null);
  const [teacherToDelete, setTeacherToDelete] = useState<AdminTeacher | null>(
    null,
  );
  const [formValues, setFormValues] = useState<TeacherFormValues>(() =>
    createEmptyTeacherForm("", defaultTeacherAvailability),
  );
  const [formError, setFormError] = useState<string | null>(null);
  const [importFile, setImportFile] = useState<File | null>(null);
  const [importError, setImportError] = useState<string | null>(null);
  const [importResult, setImportResult] =
    useState<TeacherImportResponse | null>(null);
  const [createdTeacherAccount, setCreatedTeacherAccount] =
    useState<TeacherCreatedAccount | null>(null);
  const [importInputVersion, setImportInputVersion] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [isImporting, setIsImporting] = useState(false);
  const [branchOptions, setBranchOptions] = useState<string[]>([]);
  const [isBranchOptionsLoading, setIsBranchOptionsLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [pageLimit, setPageLimit] = useState(20);
  const [totalPages, setTotalPages] = useState(1);
  const [totalItems, setTotalItems] = useState(0);
  const [summary, setSummary] = useState<AdminTeachersSummary>({
    totalItems: 0,
    activeCount: 0,
    inactiveCount: 0,
    branchCount: 0,
    activeClassesTotal: 0,
  });
  const deferredSearch = useDeferredValue(search);
  const deferredGlobalSearch = useDeferredValue(globalSearchQuery);
  const previousQueryKeyRef = useRef<string | null>(null);

  useEffect(() => {
    let isCancelled = false;

    async function loadBranchOptions() {
      try {
        const payload = await requestAdminApi<{ branches: BranchApiItem[] }>(
          "/api/branches",
          {
            method: "GET",
          },
        );

        if (isCancelled) {
          return;
        }

        setBranchOptions(
          buildBranchOptions(
            (payload.data?.branches ?? []).map((branch) => branch.name ?? ""),
          ),
        );
      } catch {
        if (!isCancelled) {
          setBranchOptions([]);
        }
      } finally {
        if (!isCancelled) {
          setIsBranchOptionsLoading(false);
        }
      }
    }

    void loadBranchOptions();

    return () => {
      isCancelled = true;
    };
  }, []);

  const combinedSearchQuery = [
    deferredSearch.trim(),
    deferredGlobalSearch.trim(),
  ]
    .filter(Boolean)
    .join(" ");
  const resolvedBranchFilter =
    !isBranchOptionsLoading &&
    branchFilter !== allBranchesLabel &&
    !normalizeTeacherBranch(branchFilter, branchOptions)
      ? allBranchesLabel
      : branchFilter;
  const requestKey = [
    combinedSearchQuery.toLowerCase(),
    resolvedBranchFilter,
    statusFilter,
    pageLimit,
  ].join("|");

  const refreshTeachers = useCallback(
    async (nextPage: number = page) => {
      setIsLoading(true);
      setError(null);

      try {
        const result = await fetchAdminTeachers({
          page: nextPage,
          limit: pageLimit,
          q: combinedSearchQuery || undefined,
          branch:
            resolvedBranchFilter === allBranchesLabel
              ? undefined
              : resolvedBranchFilter,
          status: statusFilter === "Semua" ? undefined : statusFilter,
          sort: "createdAt_asc",
        });

        setTeachers(result.teachers);
        setSummary(result.summary);
        setPage(result.pagination.page);
        setPageLimit(result.pagination.limit);
        setTotalPages(result.pagination.totalPages);
        setTotalItems(result.pagination.totalItems);
        setError(null);
      } catch (requestError) {
        setTeachers([]);
        setSummary({
          totalItems: 0,
          activeCount: 0,
          inactiveCount: 0,
          branchCount: 0,
          activeClassesTotal: 0,
        });
        setTotalPages(1);
        setTotalItems(0);
        setError(
          requestError instanceof Error
            ? requestError.message
            : "Gagal memuat daftar guru.",
        );
      } finally {
        setIsLoading(false);
      }
    },
    [combinedSearchQuery, page, pageLimit, resolvedBranchFilter, statusFilter],
  );

  const refreshTeacherViews = useCallback(
    async (nextPage: number = page) => {
      await Promise.allSettled([
        refreshTeachers(nextPage),
        Promise.resolve(onRefresh?.()),
      ]);
    },
    [onRefresh, page, refreshTeachers],
  );

  useEffect(() => {
    const filtersChanged =
      previousQueryKeyRef.current !== null &&
      previousQueryKeyRef.current !== requestKey;

    previousQueryKeyRef.current = requestKey;

    if (filtersChanged && page !== 1) {
      setPage(1);
      return;
    }

    const timerId = window.setTimeout(() => {
      void refreshTeachers(page);
    }, 0);

    return () => {
      window.clearTimeout(timerId);
    };
  }, [page, refreshTeachers, requestKey]);

  const branchFilterOptions = useMemo(
    () => [allBranchesLabel, ...branchOptions],
    [branchOptions],
  );
  const resolvedBranchOptions = branchOptions;

  const filteredTeachers = teachers;
  const activeTeachers = summary.activeCount;
  const inactiveTeachers = summary.inactiveCount;
  const isEditing = editingTeacherId !== null;
  const selectedBranchValue = formValues.branch || getDefaultBranch(branchOptions);

  const openCreateDialog = () => {
    setEditingTeacherId(null);
    setFormValues(
      createEmptyTeacherForm(
        getDefaultBranch(branchOptions),
        defaultTeacherAvailability,
      ),
    );
    setFormError(null);
    setIsFormOpen(true);
  };

  const openEditDialog = (teacher: AdminTeacher) => {
    setEditingTeacherId(teacher.id);
    setFormValues(toTeacherFormValues(teacher, branchOptions));
    setFormError(null);
    setIsFormOpen(true);
  };

  const closeFormDialog = () => {
    setIsFormOpen(false);
    setEditingTeacherId(null);
    setFormValues(
      createEmptyTeacherForm(
        getDefaultBranch(branchOptions),
        defaultTeacherAvailability,
      ),
    );
    setFormError(null);
  };

  const closeImportDialog = () => {
    setIsImportOpen(false);
    setImportFile(null);
    setImportError(null);
    setImportInputVersion((currentValue) => currentValue + 1);
  };
  const teacherNumberMap = new Map(
    filteredTeachers.map((teacher, index) => [
      teacher.id,
      (page - 1) * pageLimit + index + 1,
    ]),
  );

  const updateFormValue = <K extends keyof TeacherFormValues>(
    key: K,
    value: TeacherFormValues[K],
  ) => {
    setFormValues((currentValues) => ({
      ...currentValues,
      [key]: value,
    }));
  };

  const handleResetFilters = () => {
    setSearch("");
    setBranchFilter(allBranchesLabel);
    setStatusFilter("Semua");
  };

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const normalizedName = normalizeText(formValues.name);
    const normalizedEmail = normalizeEmail(formValues.email);
    const normalizedPassword = formValues.password.trim();
    const normalizedSubject = normalizeText(formValues.subject);
    const normalizedBranch = normalizeTeacherBranch(
      selectedBranchValue,
      resolvedBranchOptions,
    );
    const normalizedPhone = normalizePhone(formValues.phone);
    const normalizedSchedule = normalizeText(formValues.schedule);
    const normalizedActiveClasses = normalizeActiveClasses(
      formValues.activeClasses,
    );
    const normalizedClassList = normalizeClassList(formValues.classList);
    const shouldAutoGenerateCredentials =
      !isEditing && (!normalizedEmail || !normalizedPassword);

    if (!normalizedName) {
      setFormError("Nama guru wajib diisi.");
      return;
    }

    if (isEditing && !normalizedEmail) {
      setFormError("Email guru wajib diisi.");
      return;
    }

    if (normalizedEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalizedEmail)) {
      setFormError("Format email guru belum valid.");
      return;
    }

    if (normalizedPassword && normalizedPassword.length < 8) {
      setFormError("Password guru minimal 8 karakter.");
      return;
    }

    if (!normalizedSubject) {
      setFormError("Mapel wajib diisi.");
      return;
    }

    if (!normalizedBranch) {
      setFormError("Pilih cabang guru yang tersedia terlebih dahulu.");
      return;
    }

    if (!normalizedPhone) {
      setFormError("No. HP wajib diisi.");
      return;
    }

    if (!normalizedSchedule) {
      setFormError("Jadwal mengajar wajib diisi.");
      return;
    }

    if (normalizedActiveClasses === null) {
      setFormError("Kelas aktif harus berupa angka 0 atau lebih.");
      return;
    }

    if (!normalizedClassList) {
      setFormError("Kelas yang diampu wajib diisi.");
      return;
    }

    if (!normalizedClassList) {
      setFormError("Pendidikan terakhir wajib diisi.");
      return;
    }

    const duplicateTeacher = teachers.find(
      (teacher) =>
        normalizePhone(teacher.phone) === normalizedPhone &&
        teacher.id !== editingTeacherId,
    );

    if (duplicateTeacher) {
      setFormError("No. HP sudah digunakan guru lain.");
      return;
    }

    if (normalizedEmail) {
      const duplicateEmail = teachers.find(
        (teacher) =>
          normalizeEmail(teacher.email) === normalizedEmail &&
          teacher.id !== editingTeacherId,
      );

      if (duplicateEmail) {
        setFormError("Email sudah digunakan guru lain.");
        return;
      }
    }

    setIsSubmitting(true);
    setFormError(null);

    try {
      const payload = await requestAdminApi<TeacherCreateResponse>(
        editingTeacherId
          ? `/api/teachers/${encodeURIComponent(editingTeacherId)}`
          : "/api/teachers",
        {
          method: editingTeacherId ? "PUT" : "POST",
          body: JSON.stringify({
            name: normalizedName,
            ...(normalizedEmail ? { email: normalizedEmail } : {}),
            ...(normalizedPassword ? { password: normalizedPassword } : {}),
            ...(!isEditing && shouldAutoGenerateCredentials
              ? { autoGenerateCredentials: true }
              : {}),
            subject: normalizedSubject,
            branch: normalizedBranch,
            phone: normalizedPhone,
            schedule: normalizedSchedule,
            activeClasses: normalizedActiveClasses,
            classList: normalizedClassList,
            status: formValues.status,
            availability: formValues.availability,
          }),
        },
      );
      const createdTeacher = payload.data?.teacher;
      const generatedCredentials = payload.data?.generatedCredentials;

      if (!isEditing && createdTeacher) {
        const resolvedPassword = generatedCredentials?.password ?? normalizedPassword;

        if (resolvedPassword) {
          setCreatedTeacherAccount({
            teacherId: createdTeacher.id,
            teacherName: createdTeacher.name,
            email: generatedCredentials?.email ?? createdTeacher.email,
            loginCode: generatedCredentials?.loginCode ?? createdTeacher.loginCode,
            password: resolvedPassword,
            autoGeneratedEmail: generatedCredentials?.autoGeneratedEmail ?? false,
            autoGeneratedPassword:
              generatedCredentials?.autoGeneratedPassword ?? false,
          });
        }
      }

      await refreshTeacherViews();
      closeFormDialog();
    } catch (requestError) {
      setFormError(
        requestError instanceof Error
          ? requestError.message
          : "Gagal menyimpan data guru.",
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDelete = async () => {
    if (!teacherToDelete) {
      return;
    }

    setIsDeleting(true);

    try {
      await requestAdminApi(`/api/teachers/${encodeURIComponent(teacherToDelete.id)}`, {
        method: "DELETE",
      });
      await refreshTeacherViews();
      setTeacherToDelete(null);
    } catch (requestError) {
      setFormError(
        requestError instanceof Error
          ? requestError.message
          : "Gagal menghapus data guru.",
      );
    } finally {
      setIsDeleting(false);
    }
  };

  const handleToggleStatus = async (teacher: AdminTeacher) => {
    const nextStatus = teacher.status === "Aktif" ? "Nonaktif" : "Aktif";
    const nextAvailability =
      nextStatus === "Aktif"
        ? teacher.availability === "Cuti"
          ? "Tersedia"
          : teacher.availability
        : "Cuti";

    try {
      await requestAdminApi<{ teacher: AdminTeacher }>(
        `/api/teachers/${encodeURIComponent(teacher.id)}`,
        {
          method: "PUT",
          body: JSON.stringify({
            name: teacher.name,
            email: teacher.email,
            subject: teacher.subject,
            branch: teacher.branch,
            phone: teacher.phone,
            schedule: teacher.schedule,
            activeClasses: teacher.activeClasses,
            classList: teacher.classList,
            status: nextStatus,
            availability: nextAvailability,
          }),
        },
      );
      await refreshTeacherViews();
    } catch (requestError) {
      setFormError(
        requestError instanceof Error
          ? requestError.message
          : "Gagal memperbarui status guru.",
      );
    }
  };

  const handleExport = async () => {
    if (!filteredTeachers.length) {
      return;
    }

    try {
      await exportAdminTeachersCsv({
        q: combinedSearchQuery || undefined,
        branch: branchFilter === allBranchesLabel ? undefined : branchFilter,
        status: statusFilter === "Semua" ? undefined : statusFilter,
        sort: "createdAt_asc",
      });
    } catch (requestError) {
      setFormError(
        requestError instanceof Error
          ? requestError.message
          : "Gagal mengunduh export guru.",
      );
    }
  };

  const handleImportFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    setImportFile(event.target.files?.[0] ?? null);
    setImportError(null);
  };

  const handleImportSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!importFile) {
      setImportError("Pilih file Excel guru terlebih dahulu.");
      return;
    }

    setIsImporting(true);
    setImportError(null);

    try {
      const fileDataUrl = await readFileAsDataUrl(importFile);
      const fileDataBase64 = fileDataUrl.includes(",")
        ? (fileDataUrl.split(",")[1] ?? "")
        : fileDataUrl;
      const payload = await requestAdminApi<TeacherImportResponse>(
        "/api/teachers/import",
        {
          method: "POST",
          body: JSON.stringify({
            fileName: importFile.name,
            fileDataBase64,
          }),
        },
      );
      const nextImportResult = payload.data;

      if (!nextImportResult?.summary) {
        setImportError("Ringkasan hasil import guru tidak tersedia.");
        return;
      }

      await refreshTeacherViews();
      setImportResult({
        fileName: nextImportResult.fileName,
        sheetName: nextImportResult.sheetName,
        summary: nextImportResult.summary,
        details: nextImportResult.details ?? [],
      });
      closeImportDialog();
    } catch (requestError) {
      setImportError(
        requestError instanceof Error
          ? requestError.message
          : "Gagal mengimpor data guru.",
      );
    } finally {
      setIsImporting(false);
    }
  };

  const columns: AdminColumnDefinition<AdminTeacher>[] = [
    {
      key: "number",
      header: "No",
      className: "w-[84px] text-center",
      cell: (teacher) => teacherNumberMap.get(teacher.id) ?? "-",
    },
    {
      key: "name",
      header: "Nama",
      cell: (teacher) => (
        <div className="flex items-center gap-3">
          <Avatar className="rounded-full">
            <AvatarFallback className={cn(warmAvatarFallbackClassName, "rounded-full")}>
              {getInitials(teacher.name)}
            </AvatarFallback>
          </Avatar>
          <div className="min-w-0">
            <p className="truncate font-semibold text-slate-950">
              {teacher.name}
            </p>

          </div>
        </div>
      ),
    },
    {
      key: "subject",
      header: "Mapel / Cabang",
      cell: (teacher) => {
        const branches = getTeacherBranches(teacher, branchOptions);

        return (
          <div>
            <p className="font-medium text-slate-800">{teacher.subject}</p>
            {branches.length ? (
              <div className="mt-1 flex flex-wrap gap-1.5">
                {branches.map((branch) => (
                  <Badge
                    key={branch}
                    variant="outline"
                    className="border-orange-100 bg-orange-50/70 px-2 py-0.5 text-[11px] font-medium text-orange-700"
                  >
                    {branch}
                  </Badge>
                ))}
              </div>
            ) : (
              <p className="mt-1 text-xs text-slate-500">
                Cabang belum diatur
              </p>
            )}
          </div>
        );
      },
    },
    {
      key: "loginCode",
      header: "Kode Login",
      cell: (teacher) => (
        <div className="max-w-[220px]">
          <p className="truncate text-sm font-semibold text-slate-800">
            {teacher.loginCode || teacher.id}
          </p>
          {!teacher.email.endsWith("@bimbel.local") && (
            <p className="truncate text-xs text-slate-500">{teacher.email}</p>
          )}
        </div>
      ),
    },
    {
      key: "schedule",
      header: "Jadwal Mengajar",
      cell: (teacher) => (
        <p className="max-w-[220px] text-sm leading-6 text-slate-700">
          {teacher.schedule}
        </p>
      ),
    },
    {
      key: "activeClasses",
      header: "Kelas Aktif",
      cell: (teacher) => `${teacher.activeClasses} kelas`,
    },
    {
      key: "classList",
      header: "Pendidikan Terakhir",
      cell: (teacher) => (
        <p className="max-w-[240px] text-sm leading-6 text-slate-700">
          {teacher.classList}
        </p>
      ),
    },
    {
      key: "status",
      header: "Status",
      cell: (teacher) => (
        <div className="flex flex-wrap gap-2">
          <AdminStatusBadge status={teacher.status} />
          <AdminStatusBadge status={teacher.availability} />
        </div>
      ),
    },
    {
      key: "actions",
      header: "Aksi",
      cell: (teacher) => (
        <TeacherActions
          teacher={teacher}
          branchOptions={branchOptions}
          onEdit={openEditDialog}
          onDelete={setTeacherToDelete}
          onToggleStatus={handleToggleStatus}
        />
      ),
      className: "w-[196px] text-center",
    },
  ];

  return (
    <>
      <AdminSectionCard
        title="Kelola guru"
        description="Kelola data guru, filter cabang, serta atur status mengajar."
        square
        action={
          <div className="flex flex-wrap items-center gap-2 sm:gap-3">
            <Button
              variant="secondary"
              className={warmPrimaryButtonClassName}
              onClick={openCreateDialog}
            >
              <Plus className="size-4" />
              <span className="hidden sm:inline">Tambah Data</span>
              <span className="inline sm:hidden">Tambah</span>
            </Button>
            <Button
              variant="outline"
              className={warmOutlineButtonClassName}
              onClick={handleExport}
              disabled={!filteredTeachers.length}
            >
              <Download className="size-4" />
              <span className="hidden sm:inline">Export</span>
            </Button>
            <Button
              variant="outline"
              className={warmOutlineButtonClassName}
              onClick={() => setIsImportOpen(true)}
            >
              <Upload className="size-4" />
              <span className="hidden sm:inline">Import</span>
            </Button>
          </div>
        }
      >
        {isLoading ? (
          <AdminSummaryLineSkeleton className="mb-4" />
        ) : (
        <div className="mb-4 flex flex-wrap items-center gap-2 text-sm text-slate-500">
          <span>
            Menampilkan {filteredTeachers.length} dari {totalItems}{" "}
            guru.
          </span>
          <Badge variant="secondary" className="bg-slate-100 text-slate-700">
            Aktif {activeTeachers}
          </Badge>
          <Badge variant="secondary" className="bg-slate-100 text-slate-700">
            Nonaktif {inactiveTeachers}
          </Badge>
          <Badge variant="secondary" className="bg-slate-100 text-slate-700">
            Cabang {summary.branchCount}
          </Badge>
        </div>
        )}

        {isBranchOptionsLoading ? (
          <AdminSummaryLineSkeleton className="mb-4 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3" badges={2} />
        ) : null}

        {!isBranchOptionsLoading && branchOptions.length === 0 ? (
          <div className="mb-4 rounded-xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm text-amber-700">
            Belum ada cabang yang tersedia. Tambahkan cabang dari dashboard
            owner agar filter dan form guru bisa dipakai.
          </div>
        ) : null}

        {createdTeacherAccount ? (
          <div className="mb-4 rounded-xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">
            <p>
              Akun guru untuk {createdTeacherAccount.teacherName} (
              {createdTeacherAccount.teacherId}) siap dipakai login.
            </p>
            <p className="mt-2 text-xs leading-6">
              Kode Login: {createdTeacherAccount.loginCode} | Password:{" "}
              {createdTeacherAccount.password}
            </p>
            <p className="mt-1 text-xs leading-6">
              Email internal: {createdTeacherAccount.email}
            </p>
            {createdTeacherAccount.autoGeneratedEmail ||
            createdTeacherAccount.autoGeneratedPassword ? (
              <p className="mt-2 text-xs leading-6">
                Kredensial ini dibuat otomatis mengikuti pola akun guru sistem.
              </p>
            ) : null}
          </div>
        ) : null}

        {importResult ? (
          <div
            className={`mb-4 rounded-xl border px-4 py-3 text-sm ${
              importResult.summary.failedRows || importResult.summary.skippedRows
                ? "border-amber-100 bg-amber-50 text-amber-700"
                : "border-emerald-100 bg-emerald-50 text-emerald-700"
            }`}
          >
            <p>
              Import selesai dari {importResult.fileName}. Total row{" "}
              {importResult.summary.totalRows}, berhasil{" "}
              {importResult.summary.importedRows}, gagal{" "}
              {importResult.summary.failedRows}, dilewati{" "}
              {importResult.summary.skippedRows}.
            </p>
            {importResult.summary.importedRows ? (
              <p className="mt-2 text-xs leading-6">
                Kode login guru hasil import memakai ID guru di tabel. Password awal mengikuti pola `guruNNN` dari
                ID guru di tabel, misalnya `TCH-012` memakai password
                `guru012`.
              </p>
            ) : null}

            {importResult.details.length ? (
              <div className="mt-2 space-y-1 text-xs leading-6">
                {importResult.details.slice(0, 6).map((detail) => (
                  <p
                    key={`${detail.status}-${detail.rowNumber}-${detail.name}-${detail.subject}`}
                  >
                    {detail.status === "imported"
                      ? `Baris ${detail.rowNumber}: ${detail.name} -> ${detail.loginCode ?? detail.email} / ${detail.generatedPassword}`
                      : `Baris ${detail.rowNumber}: ${detail.reason ?? "Baris dilewati."}`}
                  </p>
                ))}
                {importResult.details.length > 6 ? (
                  <p>
                    +{importResult.details.length - 6} detail lain tersedia di
                    hasil import.
                  </p>
                ) : null}
              </div>
            ) : null}
          </div>
        ) : null}

        {error ? (
          <div className="mb-4 rounded-xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm text-amber-700">
            {error}
          </div>
        ) : null}

        <div className="mb-6 flex flex-col gap-3 md:flex-row md:flex-wrap">
          <div className="w-full md:flex-1">
            <Input
              className={warmFieldClassName}
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Cari nama, kode login, mapel, cabang, jadwal, atau kelas..."
            />
          </div>

          <div className="grid w-full grid-cols-2 gap-3 sm:flex sm:w-auto sm:flex-wrap">
            <div className="w-full sm:w-[220px]">
              <Select
                value={resolvedBranchFilter}
                onValueChange={setBranchFilter}
              >
                <SelectTrigger className={warmSelectTriggerClassName}>
                  <SelectValue placeholder="Cabang" />
                </SelectTrigger>
                <SelectContent className={warmSelectContentClassName}>
                  {branchFilterOptions.map((option) => (
                    <SelectItem
                      key={option}
                      value={option}
                      className={warmSelectItemClassName}
                    >
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="w-full sm:w-[160px]">
              <Select
                value={statusFilter}
                onValueChange={(value) =>
                  setStatusFilter(value as TeacherStatusFilterOption)
                }
              >
                <SelectTrigger className={warmSelectTriggerClassName}>
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent className={warmSelectContentClassName}>
                  {teacherStatusOptions.map((option) => (
                    <SelectItem
                      key={option}
                      value={option}
                      className={warmSelectItemClassName}
                    >
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <Button
            type="button"
            variant="outline"
            className={`w-full sm:w-auto ${warmOutlineButtonClassName}`}
            onClick={handleResetFilters}
          >
            <RotateCcw className="size-4" />
            Reset
          </Button>
        </div>

        <AdminDataTable
          columns={columns}
          data={filteredTeachers}
          keyExtractor={(teacher) => teacher.id}
          emptyTitle="Tidak ada guru yang cocok"
          emptyDescription="Coba ubah kata kunci pencarian atau kombinasi filter."
          isLoading={isLoading}
          square
          getRowClassName={(teacher) =>
            teacher.status === "Nonaktif"
              ? "bg-slate-50/70 hover:bg-slate-100/70"
              : undefined
          }
          minWidthClassName="min-w-[1320px]"
        />
        <div className="mt-4">
          <AdminPaginationFooter
            page={page}
            totalPages={totalPages}
            totalItems={totalItems}
            visibleCount={filteredTeachers.length}
            limit={pageLimit}
            isLoading={isLoading}
            label="guru"
            onPrevious={() => {
              setPage((currentPage) => Math.max(1, currentPage - 1));
            }}
            onNext={() => {
              setPage((currentPage) => Math.min(totalPages, currentPage + 1));
            }}
          />
        </div>
      </AdminSectionCard>

      <Dialog
        open={isFormOpen}
        onOpenChange={(open) => {
          if (!open) {
            closeFormDialog();
          }
        }}
      >
        <DialogContent
          className={`max-h-[90vh] overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none] sm:max-w-5xl ${warmOverlayPanelClassName}`}
        >
          <DialogHeader>
            <DialogTitle>
              {isEditing ? "Edit guru" : "Tambah guru baru"}
            </DialogTitle>
            <DialogDescription>
              Isi nama, mapel, cabang, no HP, jadwal, distribusi kelas, dan
              status mengajar guru.
            </DialogDescription>
          </DialogHeader>

          <form className="space-y-6" onSubmit={handleSubmit}>
            <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4">
              <TeacherField label="Nama">
                <Input
                  className={warmFieldClassName}
                  value={formValues.name}
                  onChange={(event) =>
                    updateFormValue("name", event.target.value)
                  }
                  placeholder="Nama lengkap guru"
                />
              </TeacherField>

              <TeacherField label="Email kontak/internal">
                <div className="space-y-2">
                  <Input
                    className={warmFieldClassName}
                    type="email"
                    value={formValues.email}
                    onChange={(event) =>
                      updateFormValue("email", event.target.value)
                    }
                    placeholder={
                      isEditing
                        ? "guru@email.com"
                        : "Kosongkan untuk generate otomatis"
                    }
                  />
                  {!isEditing ? (
                    <p className="text-xs leading-5 text-slate-500">
                      Login guru memakai kode akun, misalnya TCH-001. Email
                      boleh dikosongkan agar sistem membuat email internal.
                    </p>
                  ) : null}
                </div>
              </TeacherField>

              <TeacherField label="Mapel">
                <Select
                  value={formValues.subject}
                  onValueChange={(value) => updateFormValue("subject", value)}
                >
                  <SelectTrigger className={warmSelectTriggerClassName}>
                    <SelectValue placeholder="Pilih mata pelajaran" />
                  </SelectTrigger>
                  <SelectContent className={warmSelectContentClassName}>
                    {teacherSubjectOptions.map((option) => (
                      <SelectItem
                        key={option}
                        value={option}
                        className={warmSelectItemClassName}
                      >
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </TeacherField>

              <TeacherField label="Password">
                <div className="space-y-2">
                  <Input
                    className={warmFieldClassName}
                    type="password"
                    value={formValues.password}
                    onChange={(event) =>
                      updateFormValue("password", event.target.value)
                    }
                    placeholder={
                      isEditing
                        ? "Kosongkan jika tidak diubah"
                        : "Kosongkan untuk generate otomatis"
                    }
                  />
                  {!isEditing ? (
                    <p className="text-xs leading-5 text-slate-500">
                      Jika dikosongkan, password awal guru dibuat otomatis dan
                      akan ditampilkan setelah akun berhasil dibuat.
                    </p>
                  ) : null}
                </div>
              </TeacherField>

              <TeacherField label="Cabang">
                <Select
                  value={selectedBranchValue}
                  onValueChange={(value) => updateFormValue("branch", value)}
                >
                  <SelectTrigger className={warmSelectTriggerClassName}>
                    <SelectValue placeholder="Pilih cabang" />
                  </SelectTrigger>
                  <SelectContent className={warmSelectContentClassName}>
                    {resolvedBranchOptions.map((option) => (
                      <SelectItem
                        key={option}
                        value={option}
                        className={warmSelectItemClassName}
                      >
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {isBranchOptionsLoading ? (
                  <p className="text-xs text-slate-500">
                    Daftar cabang sedang dimuat...
                  </p>
                ) : null}
                {!isBranchOptionsLoading && branchOptions.length === 0 ? (
                  <p className="text-xs text-amber-600">
                    Belum ada cabang yang tersedia untuk dipilih.
                  </p>
                ) : null}
              </TeacherField>

              <TeacherField label="No HP">
                <Input
                  className={warmFieldClassName}
                  value={formValues.phone}
                  onChange={(event) =>
                    updateFormValue("phone", event.target.value)
                  }
                  placeholder="Nomor telepon aktif"
                />
              </TeacherField>

              <TeacherField label="Status">
                <Select
                  value={formValues.status}
                  onValueChange={(value) =>
                    updateFormValue("status", value as AdminTeacher["status"])
                  }
                >
                  <SelectTrigger className={warmSelectTriggerClassName}>
                    <SelectValue placeholder="Pilih status" />
                  </SelectTrigger>
                  <SelectContent className={warmSelectContentClassName}>
                    {teacherStatusOptions
                      .filter((option) => option !== "Semua")
                      .map((option) => (
                        <SelectItem
                          key={option}
                          value={option}
                          className={warmSelectItemClassName}
                        >
                          {option}
                        </SelectItem>
                      ))}
                  </SelectContent>
                </Select>
              </TeacherField>

              <TeacherField label="Ketersediaan">
                <Select
                  value={formValues.availability}
                  onValueChange={(value) =>
                    updateFormValue(
                      "availability",
                      value as AdminTeacher["availability"],
                    )
                  }
                >
                  <SelectTrigger className={warmSelectTriggerClassName}>
                    <SelectValue placeholder="Pilih ketersediaan" />
                  </SelectTrigger>
                  <SelectContent className={warmSelectContentClassName}>
                    {teacherAvailabilityOptions.map((option) => (
                      <SelectItem
                        key={option}
                        value={option}
                        className={warmSelectItemClassName}
                      >
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </TeacherField>

              <div className="sm:col-span-2">
                <TeacherField label="Pendidikan Terakhir">
                  <Input
                    className={warmFieldClassName}
                    value={formValues.classList}
                    onChange={(event) =>
                      updateFormValue("classList", event.target.value)
                    }
                    placeholder="Contoh: S1 Matematika"
                  />
                </TeacherField>
              </div>
            </div>

            {formError ? (
              <p className="rounded-lg border border-rose-100 bg-rose-50 px-3 py-2 text-sm text-rose-600">
                {formError}
              </p>
            ) : null}

            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                className={warmOutlineButtonClassName}
                onClick={() => closeFormDialog()}
              >
                Batal
              </Button>
              <Button
                type="submit"
                variant="secondary"
                className={warmPrimaryButtonClassName}
                disabled={isSubmitting}
              >
                {isSubmitting
                  ? "Menyimpan..."
                  : isEditing
                    ? "Simpan perubahan"
                    : "Tambah guru"}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <Dialog
        open={isImportOpen}
        onOpenChange={(open) => {
          if (!open) {
            closeImportDialog();
          }
        }}
      >
        <DialogContent className={`max-h-[90vh] overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none] sm:max-w-xl ${warmOverlayPanelClassName}`}>
          <DialogHeader>
            <DialogTitle>Import data guru</DialogTitle>
            <DialogDescription>
              Upload file Excel guru. Sistem akan membaca nama guru, bidang,
              pendidikan terakhir, dan cabang. Field lain tetap bisa diisi
              otomatis bila kolom tambahannya belum tersedia.
            </DialogDescription>
          </DialogHeader>

          <form className="space-y-5" onSubmit={handleImportSubmit}>
            <div className="rounded-[22px] border border-slate-200/80 bg-gradient-to-r from-white to-orange-50/45 px-4 py-3 text-sm leading-6 text-slate-600 shadow-[0_12px_26px_-22px_rgba(249,115,22,0.16)]">
              Header utama yang dibaca: {teacherImportColumns.join(", ")}.
              Penamaan cabang harus sesuai dengan standar sistem pusat. Sistem
              juga tetap menerima kolom tambahan seperti email, nomor telepon, jadwal,
              status, atau ketersediaan waktu jika nanti ada.
            </div>

            <TeacherField label="File Excel">
              <input
                key={importInputVersion}
                type="file"
                accept=".xlsx,.xls,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/csv"
                onChange={handleImportFileChange}
                className={warmFileInputClassName}
              />
            </TeacherField>

            {importError ? (
              <p className="rounded-lg border border-rose-100 bg-rose-50 px-3 py-2 text-sm text-rose-600">
                {importError}
              </p>
            ) : null}

            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                className={warmOutlineButtonClassName}
                onClick={closeImportDialog}
              >
                Batal
              </Button>
              <Button
                type="submit"
                variant="secondary"
                className={warmPrimaryButtonClassName}
                disabled={isImporting}
              >
                {isImporting ? "Mengimpor..." : "Import Excel"}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <Dialog
        open={Boolean(teacherToDelete)}
        onOpenChange={(open) => {
          if (!open) {
            setTeacherToDelete(null);
          }
        }}
      >
        <DialogContent className={warmOverlayPanelClassName}>
          <DialogHeader>
            <DialogTitle>Hapus data guru</DialogTitle>
            <DialogDescription>
              Data guru yang dihapus akan hilang dari tabel yang sedang aktif.
            </DialogDescription>
          </DialogHeader>

          <div className="rounded-[22px] border border-slate-200/80 bg-gradient-to-r from-white to-orange-50/45 px-4 py-3 text-sm leading-6 text-slate-600 shadow-[0_12px_26px_-22px_rgba(249,115,22,0.16)]">
            {teacherToDelete
              ? `Hapus ${teacherToDelete.name} dengan mapel ${teacherToDelete.subject}?`
              : "Pilih guru yang ingin dihapus."}
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              className={warmOutlineButtonClassName}
              onClick={() => setTeacherToDelete(null)}
            >
              Batal
            </Button>
            <Button
              type="button"
              variant="destructive"
              className="focus-visible:ring-orange-500/10"
              disabled={isDeleting}
              onClick={handleDelete}
            >
              {isDeleting ? "Menghapus..." : "Hapus"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
